### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by garrylea** [medooze/media-server-client-js#1]
when I run the second command 'npm run-script dist' , I get the following error:

===============================

> medooze-media-server-client@1.2.0 dist /Users/lichao/Downloads/media-server-client-js
> browserify --standalone MediaServerClient lib/MediaServerClient.js -o dist/medooze-media-server-client.js && cp dist/* demo/www

sh: browserify: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! medooze-media-server-client@1.2.0 dist: `browserify --standalone MediaServerClient lib/MediaServerClient.js -o dist/medooze-media-server-client.js && cp dist/* demo/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the medooze-media-server-client@1.2.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lichao/.npm/_logs/2018-11-15T03_09_09_545Z-debug.log

**Comment by murillo128** [comment]
You need to install browerify globally: 

```
npm i browserify
```

will update the docs
