### ISSUE TITLE
Wrong PeerConnectionClient close implementation

### ISSUE THREAD

**Issue by jrpedrianes** [medooze/media-server-client-js#3]
The close method seems have some issues.
https://github.com/medooze/media-server-client-js/blob/master/lib/PeerConnectionClient.js#L490

I think that the correct one should be:
`
	stop()
	{	
		//Stop peerconnection
		this.pc.close();
		//Stop namespace
		this.ns.close();
		//Null
		this.pc = null;
		this.ns = null;
	}
`

Instead to call to `stop` method, we need to call to `close` method, to stop the peer connection and the namespace

**Comment by murillo128** [comment]
Fixed, thank you!
